/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * Copyright [2020-2022] Renesas Electronics Corporation and/or its affiliates.  All Rights Reserved.
 *
 * This software and documentation are supplied by Renesas Electronics Corporation and/or its affiliates and may only
 * be used with products of Renesas Electronics Corp. and its affiliates ("Renesas").  No other uses are authorized.
 * Renesas products are sold pursuant to Renesas terms and conditions of sale.  Purchasers are solely responsible for
 * the selection and use of Renesas products and Renesas assumes no liability.  No license, express or implied, to any
 * intellectual property right is granted by Renesas.  This software is protected under all applicable laws, including
 * copyright laws. Renesas reserves the right to change or discontinue this software and/or this documentation.
 * THE SOFTWARE AND DOCUMENTATION IS DELIVERED TO YOU "AS IS," AND RENESAS MAKES NO REPRESENTATIONS OR WARRANTIES, AND
 * TO THE FULLEST EXTENT PERMISSIBLE UNDER APPLICABLE LAW, DISCLAIMS ALL WARRANTIES, WHETHER EXPLICITLY OR IMPLICITLY,
 * INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NONINFRINGEMENT, WITH RESPECT TO THE
 * SOFTWARE OR DOCUMENTATION.  RENESAS SHALL HAVE NO LIABILITY ARISING OUT OF ANY SECURITY VULNERABILITY OR BREACH.
 * TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT WILL RENESAS BE LIABLE TO YOU IN CONNECTION WITH THE SOFTWARE OR
 * DOCUMENTATION (OR ANY PERSON OR ENTITY CLAIMING RIGHTS DERIVED FROM YOU) FOR ANY LOSS, DAMAGES, OR CLAIMS WHATSOEVER,
 * INCLUDING, WITHOUT LIMITATION, ANY DIRECT, CONSEQUENTIAL, SPECIAL, INDIRECT, PUNITIVE, OR INCIDENTAL DAMAGES; ANY
 * LOST PROFITS, OTHER ECONOMIC DAMAGE, PROPERTY DAMAGE, OR PERSONAL INJURY; AND EVEN IF RENESAS HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH LOSS, DAMAGES, CLAIMS OR COSTS.
 **********************************************************************************************************************/

#include "common_utils.h"
#include "ov5647.h"
#include "cru_ep.h"
#include "SerialCompatibility.h"

/*******************************************************************************************************************//**
 * @addtogroup r_cru_ep
 * @{
 **********************************************************************************************************************/
FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

/*********************************************************************************************************************
 * main() is generated by the RZA3UL Configuration editor and is used to generate threads if an RTOS is used.
 * This function is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_err_t err = FSP_SUCCESS;
    uint8_t *  capture_bufadr = NULL;

    R_IOPORT_Open(&g_ioport_ctrl, &g_bsp_pin_cfg);
    R_BSP_PinAccessEnable();

    Serial_begin(115200);
    R_BSP_SoftwareDelay(10, BSP_DELAY_UNITS_SECONDS);

    /* Initialize CRU */
    err = cru_open();
    if (FSP_SUCCESS != err)
    {
        Serial_println((uint8_t*)" ** CRU INIT FAILED ** \r\n");
        return;
    }

    err = cru_start();
    if (FSP_SUCCESS != err)
    {
        Serial_println((uint8_t*)" ** CRU START FAILED ** \r\n");
        return;
    }

    /* Initialize COMS Camera */
    R_BSP_PinWrite((bsp_io_port_pin_t) BSP_IO_PORT_16_PIN_00, BSP_IO_LEVEL_HIGH); /* CAM1_PWR */

    ov5647_config();

    /* Set display address for each layer */

    while (true) {
        /* Get capture buffer address. */
        do{
            cru_get_buffer (&capture_bufadr);
        }while(capture_bufadr == NULL);

        Serial_print((uint8_t*)"Ping :D ");

        int y, u, v, r, g, b, idx = 0;
        for (int i = 0; i < 720; i++) {
            for (int j = 0; j < 1280; j += 2) {
                y = capture_bufadr[idx + 0]; //y0
                u = capture_bufadr[idx + 1]; //u0
                v = capture_bufadr[idx + 3]; //v0

                r = y + 1.4065 * (v - 128);              //r0
                g = y - 0.3455 * (u - 128) - 0.7169 * (v - 128); //g0
                b = y + 1.1790 * (u - 128);              //b0

                if (r < 0)
                    r = 0;
                else if (r > 255)
                    r = 255;
                if (g < 0)
                    g = 0;
                else if (g > 255)
                    g = 255;
                if (b < 0)
                    b = 0;
                else if (b > 255)
                    b = 255;

//                Serial_print_val(((r << 16) | (g << 8) | b)); Serial_print((uint8_t*)" ");

                //second pixel
                u = capture_bufadr[idx + 1]; //u0
                y = capture_bufadr[idx + 2]; //y1
                v = capture_bufadr[idx + 3]; //v0

                r = y + 1.4065 * (v - 128);              //r1
                g = y - 0.3455 * (u - 128) - 0.7169 * (v - 128); //g1
                b = y + 1.1790 * (u - 128);              //b1

                if (r < 0)
                    r = 0;
                else if (r > 255)
                    r = 255;
                if (g < 0)
                    g = 0;
                else if (g > 255)
                    g = 255;
                if (b < 0)
                    b = 0;
                else if (b > 255)
                    b = 255;

                idx += 4;

//                Serial_print_val(img[i][j][0]); Serial_print((uint8_t*)" ");
//                Serial_print_val(img[i][j][1]); Serial_print((uint8_t*)" ");
//                Serial_println_val(img[i][j][2]);
//
//                Serial_print_val(img[i][j + 1][0]); Serial_print((uint8_t*)" ");
//                Serial_print_val(img[i][j + 1][1]); Serial_print((uint8_t*)" ");
//                Serial_println_val(img[i][j + 1][2]);

//                if (i % 10 == 0 && j % 10 == 0) {
//                    int gray = 0.299 * img[i][j][0] + 0.587 * img[i][j][1] + 0.114 * img[i][j][2];
//                    Serial_print_val(gray); Serial_print((uint8_t*)" ");
//                }

//                Serial_print_val(((r << 16) | (g << 8) | b)); Serial_print((uint8_t*)" ");

                if (i % 10 == 0 && j % 10 == 0) {
                    Serial_print_val(((r << 16) | (g << 8) | b)); Serial_print((uint8_t*)" ");
                }
            }
        }
        Serial_println((uint8_t*)"\n\n");

        R_BSP_SoftwareDelay(5, BSP_DELAY_UNITS_SECONDS);
    }
}

/***********************************************************************************************************************
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
        /* Initialize MMU. */
        R_MMU_Open (&g_mmu_ctrl, &g_mmu_cfg);
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */
        /* Configure pins. */
        R_IOPORT_Open (&g_ioport_ctrl, &g_bsp_pin_cfg);
    }
}
/**********************************************************************************************************************
 * @} (end addtogroup r_cru_ep)
**********************************************************************************************************************/
