#include "hal_data.h"
#include "SerialCompatibility.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

/*******************************************************************************************************************//**
 * main() is generated by the RZA3UL Configuration editor and is used to generate threads if an RTOS is used.
 * This function is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    Serial.begin(115200);
    Serial.println((uint8_t*)"Hey!");

    int32_t *ram = (int32_t*)(0x28000000 + 0x10000000);
    int32_t ram_length = 0x8000000, mod = 1000000007, add = 0x28000000 + 0x10000000;

    int fib1 = 1, fib2 = 1, fib3;
    fib1 = 1;
    fib2 = 1;
    for (int i = 0; i < 0xFDE800; i += 1024) {
        fib3 = (fib1 + fib2) % mod;
        *(ram + i) = fib3;
        fib1 = fib2;
        fib2 = fib3;
        if ((i / 256) % 1000 == 0) {
            Serial.println(i);
            Serial.println(add + i);
        }
    }

    Serial.println((uint8_t*)"Write success!");

    fib1 = 1;
    fib2 = 1;
    for (int i = 0; i < 0xFDE800; i += 1024) {
        fib3 = (fib1 + fib2) % mod;
        if (*(ram + i) != fib3) {
            Serial.println((uint8_t*)"Fail");
            //assert(1 == 0);
        }
        //assert(*(ram + i) == fib3);
        fib1 = fib2;
        fib2 = fib3;
    }

    Serial.println((uint8_t*)"Success");

    while (1) {
        R_BSP_SoftwareDelay(1000, BSP_DELAY_UNITS_MILLISECONDS);
    }
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
        /* Initialize MMU. */
        R_MMU_Open (&g_mmu_ctrl, &g_mmu_cfg);
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&g_ioport_ctrl, &g_bsp_pin_cfg);
    }
}
